# Generated by Django 4.2.1 on 2023-05-06 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Halls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("stage", models.CharField(max_length=30)),
                ("bulding", models.CharField(max_length=5)),
                ("spcial", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Halls",
            },
        ),
        migrations.AlterField(
            model_name="doctors",
            name="work_days",
            field=models.CharField(
                choices=[
                    ("sat", "sat"),
                    ("sun", "sun"),
                    ("mon", "mon"),
                    ("tue", "tue"),
                    ("wed", "wed"),
                    ("thur", "thur"),
                ],
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("full_name", models.CharField(max_length=200)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("Group-A", "Group-A"),
                            ("Group-B", "Group-B"),
                            ("Group-C", "Group-C"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "group_split",
                    models.CharField(
                        choices=[
                            ("G-1", "G-1"),
                            ("G-2", "G-2"),
                            ("G-3", "G-3"),
                            ("G-4", "G-4"),
                            ("G-5", "G-5"),
                            ("G-6", "G-6"),
                            ("G-7", "G-7"),
                            ("G-8", "G-8"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.doctors"
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.halls"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Students",
            },
        ),
        migrations.AddField(
            model_name="halls",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.doctors"
            ),
        ),
    ]
