# Generated by Django 4.2.1 on 2023-05-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_halls_alter_doctors_work_days_students_halls_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.doctors",
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="hall",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="app.halls"
            ),
        ),
    ]
