# Generated by Django 4.2.1 on 2023-05-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_students_doctor_alter_students_hall"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctors",
            name="late_time",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="doctors",
            name="rate",
            field=models.CharField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default="",
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doctors",
            name="work_days",
            field=models.TextField(blank=True),
        ),
    ]
