# Generated by Django 4.2.1 on 2023-05-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_doctors_late_time_doctors_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="rate",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ],
                max_length=2,
            ),
        ),
    ]
