# Generated by Django 4.2.1 on 2023-05-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_doctors_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
