# Generated by Django 4.2.1 on 2023-05-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_doctors_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctors",
            name="job_code",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
